alexandru_optica_app/urls.py
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Copyright © Simon ANDRÉ <simon@emencia.com>
# project: AlexandruOpticaApp
# github: https://github.com/boot-sandre/alexandru-optica-app/
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.urls.resolvers import URLPattern, URLResolver

urlpatterns: list[URLPattern | URLResolver] = [
    path(route="admin/", view=admin.site.urls),
    path(route="", view=include("optica_app.urls")),
] + static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

optica_app/urls.py
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Copyright © Simon ANDRÉ <simon@emencia.com>
# project: AlexandruOpticaApp
# github: https://github.com/boot-sandre/alexandru-optica-app/
from django.urls import path

from optica_app.views import home, view_index, order_view, identity_form_view, tunnel_form_view

app_name = 'optica_app'

urlpatterns = [
    path("", view_index, name="index"),
    path("home/", home, name="home"),
    path('order/', order_view, name='order'),
    path('identity/', identity_form_view, name='identity'),
    path('tunnel/', tunnel_form_view, name='tunnel'),
]

optica_app/models.py
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Copyright © Simon ANDRÉ <simon@emencia.com>
# project: AlexandruOpticaApp
# github: https://github.com/boot-sandre/alexandru-optica-app/
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.db import models


class Order(models.Model):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="orders"
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    def total_price(self) -> Decimal:
        return Decimal(
            self.products.aggregate(models.Sum("price"))["price__sum"]
            or Decimal("0.00")
        )

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Orders"

    def __str__(self):
        return f"ODR_{self.pk:06}"


class Identity(models.Model):
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name="identities"
    )
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Identity"
        verbose_name_plural = "Identities"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Contact(models.Model):
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name="contacts"
    )
    phone_regex = RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message="Phone number must be entered in the format: '+999999999'. "
        "Up to 15 digits allowed.",
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)

    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"

    def __str__(self):
        return self.phone_number


class Institution(models.Model):
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name="institutions"
    )
    title = models.CharField(max_length=255)
    address = models.TextField()

    class Meta:
        verbose_name = "Institution"
        verbose_name_plural = "Institutions"

    def __str__(self):
        return self.title


class PrescriptionDetail(models.Model):
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name="prescriptions"
    )
    # Validators for the optical range
    optical_range_validator = [
        MinValueValidator(Decimal("-20.00")),
        MaxValueValidator(Decimal("20.00")),
    ]
    axis_range_validator = [
        MinValueValidator(0),
        MaxValueValidator(180),
    ]
    pd_range_validator = [
        MinValueValidator(Decimal("50.0")),
        MaxValueValidator(Decimal("70.0")),
    ]

    # Fields for distance vision (Fare)
    fare_od_spheric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    fare_od_cylindric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    fare_od_axis = models.IntegerField(
        null=True,
        blank=True,
        validators=axis_range_validator,
    )

    fare_os_spheric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    fare_os_cylindric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    fare_os_axis = models.IntegerField(
        null=True,
        blank=True,
        validators=axis_range_validator,
    )

    fare_pupillary_distance = models.DecimalField(
        max_digits=5,
        decimal_places=1,
        null=True,
        blank=True,
        validators=pd_range_validator,
    )

    # Fields for near vision (Aproape)
    aproape_od_spheric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    aproape_od_cylindric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    aproape_od_axis = models.IntegerField(
        null=True,
        blank=True,
        validators=axis_range_validator,
    )

    aproape_os_spheric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    aproape_os_cylindric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    aproape_os_axis = models.IntegerField(
        null=True,
        blank=True,
        validators=axis_range_validator,
    )

    aproape_pupillary_distance = models.DecimalField(
        max_digits=5,
        decimal_places=1,
        null=True,
        blank=True,
        validators=pd_range_validator,
    )

    # Fields for intermediate vision (Intermediar)
    intermediar_od_spheric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    intermediar_od_cylindric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    intermediar_od_axis = models.IntegerField(
        null=True,
        blank=True,
        validators=axis_range_validator,
    )

    intermediar_os_spheric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    intermediar_os_cylindric = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=optical_range_validator,
    )
    intermediar_os_axis = models.IntegerField(
        null=True,
        blank=True,
        validators=axis_range_validator,
    )

    intermediar_pupillary_distance = models.DecimalField(
        max_digits=5,
        decimal_places=1,
        null=True,
        blank=True,
        validators=pd_range_validator,
    )

    class Meta:
        verbose_name = "Prescription Detail"
        verbose_name_plural = "Prescription Details"

    def __str__(self):
        return f"Prescription for Order {self.order.pk}"


class Product(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="products")
    price = models.DecimalField(
        max_digits=10, decimal_places=2, validators=[MinValueValidator(0.00)]
    )
    frame = models.ForeignKey(
        "Frame", on_delete=models.PROTECT, related_name="product_set"
    )
    glass_type = models.ForeignKey(
        "GlassType", on_delete=models.PROTECT, related_name="product_set"
    )
    lens = models.ForeignKey(
        "Lens", on_delete=models.PROTECT, related_name="product_set"
    )

    def __str__(self):
        return f"{self.frame} - {self.glass_type} - {self.lens}"


class Frame(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class GlassType(models.Model):
    DISTANCE_CHOICES = [
        ("FAR", "Far"),
        ("MEDIUM", "Medium"),
        ("NEAR", "Near"),
    ]
    TREATMENT_CHOICES = [
        ("POLARIZED", "Polarized"),
        ("UV_PROTECTION", "UV Protection"),
        ("ANTI_REFLECTIVE", "Anti-Reflective"),
    ]

    distance = models.CharField(
        max_length=100,
        choices=DISTANCE_CHOICES,
        default="NEAR",
        verbose_name="Distance",
    )
    treatment = models.CharField(
        max_length=100,
        choices=TREATMENT_CHOICES,
        verbose_name="Tratament",
        blank=True,
        null=True,
    )

    def __str__(self):
        distance_display = self.get_distance_display()
        treatment_display = (
            f", {self.get_treatment_display()}" if self.treatment else ""
        )
        return f"{distance_display}{treatment_display}"


class Lens(models.Model):
    title = models.TextField()

    def __str__(self):
        return self.title


class Voucher(models.Model):
    PAYMENT_CHOICES = [
        ("CASH", "Cash"),
        ("CARD", "Card"),
        ("IGC", "ItsGetComplicated"),
    ]
    orders = models.ManyToManyField(Order, related_name="vouchers")
    payment_method = models.TextField("Payment Method", choices=PAYMENT_CHOICES)

    def __str__(self):
        orders_display = [str(ord) for ord in self.orders.all()]
        # vouchers_display = [str(vou) for vou in self.voucher_lines.all()]
        return f"{orders_display}"

    def orders_total_price(self) -> Decimal:
        return Decimal(
            self.orders.aggregate(models.Sum("products__price"))["products__price__sum"]
            or Decimal("0.00")
        )

    def voucher_lines_total_amount(self) -> Decimal:
        return Decimal(
            self.voucher_lines.aggregate(models.Sum("amount"))["amount__sum"]
            or Decimal("0.00")
        )

    def rest_amount(self) -> Decimal:
        return Decimal(self.orders_total_price() - self.voucher_lines_total_amount())


class VoucherLine(models.Model):
    voucher = models.ForeignKey(
        Voucher, on_delete=models.PROTECT, related_name="voucher_lines"
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_date = models.DateField()

optica_app/forms.py
from django import forms
from .models import Identity, Contact, Institution, Order, PrescriptionDetail, Product, Frame, GlassType, Lens, Voucher, VoucherLine


class IdentityForm(forms.ModelForm):
    class Meta:
        model = Identity
        fields = '__all__'

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

class InstitutionForm(forms.ModelForm):
    class Meta:
        model = Institution
        fields = '__all__'

class PrescriptionDetailForm(forms.ModelForm):
    class Meta:
        model = PrescriptionDetail
        fields = '__all__'

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class FrameForm(forms.ModelForm):
    class Meta:
        model = Frame
        fields = '__all__'

class GlassTypeForm(forms.ModelForm):
    class Meta:
        model = GlassType
        fields = '__all__'

class LensForm(forms.ModelForm):
    class Meta:
        model = Lens
        fields = '__all__'

class VoucherForm(forms.ModelForm):
    class Meta:
        model = Voucher
        fields = '__all__'

class VoucherLineForm(forms.ModelForm):
    class Meta:
        model = VoucherLine
        fields = '__all__'

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

class TunnelForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

optica_app/views.py
from django.shortcuts import redirect, render
from .models import Order, Identity
from .forms import ContactForm, FrameForm, GlassTypeForm, InstitutionForm, LensForm, OrderForm, IdentityForm, PrescriptionDetailForm, ProductForm



def view_index(request):
    order = Order.objects.get(pk=1)
    identity = Identity.objects.get(order=order)
    return render(request, 'optica_app/home.html', {'order': order, 'identity': identity})

def home(request):
    return render(request, 'optica_app/index.html')


def order_view(request):
    form = OrderForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = OrderForm()

    context = {'form': form}
    return render(request, 'optica_app/form_order.html', context)


def identity_form_view(request):
    form = IdentityForm()
    if request.method == 'POST':
        form = IdentityForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('optica_app:identity')
        form = IdentityForm()

    context = {'form': form}
    return render(request, 'optica_app/form_identity.html', context)



def tunnel_form_view(request):
    order_form = OrderForm(request.POST or None)
    identity_form = IdentityForm(request.POST or None)
    contact_form = ContactForm(request.POST or None)
    institution_form = InstitutionForm(request.POST or None)
    prescription_detail_form = PrescriptionDetailForm(request.POST or None)
    product_form = ProductForm(request.POST or None)
    frame_form = FrameForm(request.POST or None)
    glass_type_form = GlassTypeForm(request.POST or None)
    lens_form = LensForm(request.POST or None)

    if all([order_form.is_valid(), identity_form.is_valid(), contact_form.is_valid(), institution_form.is_valid(), prescription_detail_form.is_valid(), product_form.is_valid(), frame_form.is_valid(), glass_type_form.is_valid(), lens_form.is_valid()]):
        order_form.save()
        identity_form.save()
        contact_form.save()
        institution_form.save()
        prescription_detail_form.save()
        product_form.save()
        frame_form.save()
        glass_type_form.save()
        lens_form.save()

        return redirect('optica_app:identity')

    context = {
        'order_form': order_form,
        'identity_form': identity_form,
        'contact_form': contact_form,
        'institution_form': institution_form,
        'prescription_detail_form': prescription_detail_form,
        'product_form': product_form,
        'frame_form': frame_form,
        'glass_type_form': glass_type_form,
        'lens_form': lens_form,
    }
    return render(request, 'optica_app/form_tunnel.html', context)

optica_app/templates/optica_app/base.html
<!-- base.html -->
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% trans "Alexandru Optica App" %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://unpkg.com/@tailwindcss/custom-forms/dist/custom-forms.min.css" rel="stylesheet" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap");
        html {
            font-family: "Poppins", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
        }
    </style>
</head>
<body>
    <div class="flex flex-col min-h-screen">
        <header class="bg-green-700 text-white text-center py-4">
            <h1 class="text-4xl">{% trans "Alexandru Optica App" %}</h1>
        </header>
        <nav class="bg-gray-200 py-2">
            <ul class="flex justify-center space-x-4">
                <li><a href="/optica" class="hover:text-blue-500">{% trans "Home" %}</a></li>
                <li><a href="{% url 'optica_app:order' %}" class="hover:text-blue-500">{% trans "Order" %}</a></li>
                <li><a href="{% url 'optica_app:identity' %}" class="hover:text-blue-500">{% trans "Identity" %}</a></li>
                <li><a href="{% url 'optica_app:tunnel' %}" class="hover:text-blue-500">{% trans "Tunnel" %}</a></li>
                <li><a href="/optica/despre" class="hover:text-blue-500">{% trans "About" %}</a></li>
                <li><a href="/optica/legatura" class="hover:text-blue-500">{% trans "Contact" %}</a></li>
            </ul>
        </nav>
        <main class="flex-grow p-4 bg-gray-800">
            {% block content %}{% endblock %}
        </main>
        <footer class="bg-green-700 text-white text-center py-4">
            <p>©2024 {% trans "Alexandru Optica App" %}.</p>
        </footer>
    </div>
</body>
</html>

optica_app/templates/optica_app/form_identity.html
<!-- optica_app/form_identity.html -->
{% extends 'optica_app/base.html' %}

{% block content %}
    <div class="flex justify-center h-screen">
        <div class="w-full max-w-xs">
            <form action="identity" method="POST" class="bg-gray-300 shadow-md rounded px-4 pt-6 pb-8 mb-4">
        {% csrf_token %}
                <h1 class="font-bold text-xl mb-2">Identity Form</h1>
        {{ form.as_p }}
                <input type="submit" value="Submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
    </form>
        </div>
    </div>
{% endblock %}

optica_app/templates/optica_app/form_order.html
<!-- optica_app/form_order.html -->
{% extends 'optica_app/base.html' %}

{% block content %}
    <div class="flex justify-center h-screen">
        <div class="w-full max-w-xs">
            <form action="order" method="POST" class="bg-gray-300 shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
                <h1 class="font-bold text-xl mb-2">Order Form</h1>
        {{ form.as_p }}
                <input type="submit" value="Submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
    </form>
        </div>
    </div>
{% endblock %}

optica_app/templates/optica_app/form_tunnel.html
<!-- optica_app/form_tunnel.html -->
{% extends 'optica_app/base.html' %}

{% block content %}
    <div class="flex justify-center h-screen">
        <div class="w-full max-w-xs">
            <form action="{% url 'optica_app:tunnel' %}" method="post" class="bg-gray-300 shadow-md rounded px-4 pt-6 pb-8 mb-4">
                {% csrf_token %}
                <h1 class="font-bold text-xl mb-2">Tunnel Form</h1>
                {{ order_form }}
                {{ identity_form }}
                {{ contact_form }}
                {{ institution_form }}
                {{ prescription_detail_form }}
                {{ product_form }}
                {{ frame_form }}
                {{ glass_type_form }}
                {{ lens_form }}
                <input type="submit" value="Submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
    </form>
        </div>
    </div>
{% endblock content %}

optica_app/templates/optica_app/home.html
{% extends "optica_app/base.html" %}

{% block content %}
<h1 class="text-center text-3xl mt-4">Optică ușoară</h1>
{% endblock %}